name: Scrape latest data

on:
  push:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 */2 * *'

jobs:
  scheduled:
    runs-on: ubuntu-latest
    steps:
    - name: Check out this repo
      uses: actions/checkout@v2
    - name: Fetch latest data
      run: |-
        curl https://hacker-news.firebaseio.com/v0/topstories.json\?print\=pretty | jq . > data/$(date -u +"%Y-%m-%d").json
    - name: Commit and push if it changed
      run: |-
        git config user.name "Automated"
        git config user.email "actions@users.noreply.github.com"
        git add -A
        timestamp=$(date -u +"%Y-%m-%d")
        git commit -m "Latest data: ${timestamp}" || exit 0
        git push
